services:
  postgres:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_USER: admin  
      POSTGRES_PASSWORD: 123  
      POSTGRES_DB: db_chatbot 
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data  # Use relative path for the current directory

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com  
      PGADMIN_DEFAULT_PASSWORD: admin  
    ports:
      - "8081:80"  
    depends_on:
      - postgres
  qdrant:
    image: qdrant/qdrant
    ports:
      - "6333:6333" # Qdrant API port
      - "6334:6334" # Qdrant gRPC port
    volumes:
      - ./qdrant_data:/qdrant/storage # Persistent storage for Qdrant data
    restart: unless-stopped
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: ["redis-server", "--appendonly", "yes"]

  redisinsight:
    image: redislabs/redisinsight:1.14.0
    container_name: redis_insight
    restart: always
    ports:
      - "8001:8001"
    environment:
      - REDIS_INSIGHT_DEFAULT_MODE=standalone
    depends_on:
      - redis
  minio:
    image: minio/minio:RELEASE.2025-04-03T14-56-28Z
    container_name: minio
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: thaco@1234
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./minio_data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local

networks:
  rag-system-net:
